# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dark" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

title                    : "Levente Laczkó"
title_separator          : " "
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Levente Laczkó"
description              : "Personal GitHub pages site"
url                      : "https://laczkol.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : laczkol/laczkol.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

include:
  - _page
  - _about
  - _post
  - _research
  - _publications
