# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dark" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

title                    : "laczkol"
title_separator          : " "
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Levente Laczkó"
description              : "Personal GitHub pages site"
url                      : "https://laczkol.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : laczkol/laczkol.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

include:
  - _pages
  - _posts

author:
  name   : "Levente Laczkó"
  avatar : "/assets/ll.png"
  bio    : "Interested in bioinformatics and biodiversity research."
  email  : "laczko.levente@med.unideb.hu"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/laczkol"
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google"
      url: "https://scholar.google.com/citations?hl=hu&user=FQFGDH4AAAAJ&view_op=list_works&sortby=pubdate"
    - label: "keybase: laczkolevente"
      icon: "fab fa-fw fa-keybase"
      url: "https://keybase.io/laczkolevente"

permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

defaults:
  # _posts
  - scope:
      path: "/"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false # true
      share: false
      related: false
